# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

services:
  - docker

# We don't actually use anything java, but this feels the least jarring "language"
language: java

# Even though this shouldn't be needed, one build failed because of SSH known hosts:
# https://travis-ci.org/openzipkin/docker-zipkin/builds/78704161
addons:
  ssh_known_hosts: github.com

# Special tags are used to trigger these Travis CI runs
branches:
  only:
    - /^release-.*$/

# jq is used in release.sh to parse the responses of the quay.io API
install:
  - sudo wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
  - sudo chmod o+x /usr/local/bin/jq

before_script:
  # The release process pushes to GitHub multiple times; will use these credentials
  - openssl aes-256-cbc -K $encrypted_1f60458c9a9e_key -iv $encrypted_1f60458c9a9e_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - chmod 600 .travis/deploy_key
  - eval "$(ssh-agent)"
  - ssh-add .travis/deploy_key
  # We also need to use a write-able git remote
  - git remote set-url origin "git@github.com:openzipkin/docker-zipkin.git"
  # Log in to Docker Hub, needed to mirror images built on quay.io
  - docker login -e abesto0+docker-zipkin-deployer@gmail.com -u dockerzipkindeployer -p "$DOCKERHUB_PASSWORD"

script:
 # Also known as doit.sh
 - ./release.sh $TRAVIS_TAG

env:
  global:
    # The release process syncs minor and major version tags to the newly built subminor version tag
    # via the quay.io API, using these credentials.
    - secure: "acmhzKdohRCGlYnUISPlA2uXOeq+YhKJrLCr8wH9sQmb4mX+IuxxidxTxcqpKPD/Mi5YbAvVVPbWU5F763EAPkbMgI2Gk0HObdRSNyx0yrJ4aTBGuQRCz1Wmd7UFoILm4w+XWcZTnd3xXguEFliqYxjNoIuhCF21A6xEFpJotgs="
    # The release process pushes images to Docker Hub, using these credentials
    - secure: "c6OUybEaMzU5aBtl9sNAyV60j4VqxPWMxvmpk8VUQmKz1qRXh/3BOVNTvBCrWQHa/rzhMOxSPQZes01ZNcYMo3XykQOcNf6hwqcobeAMkK6Ji0eaw4sOJ1IVneUI1SvseewD53KOa3hrrlY2wI1cR6SJO+5G7TSuhfZiQ9wMS7E="
