cassandra:
  image: openzipkin/zipkin-cassandra:1.19.1
  ports:
    - 9042:9042
collector:
  image: openzipkin/zipkin-collector:1.19.1
  environment:
    - TRANSPORT_TYPE=scribe
    - STORAGE_TYPE=cassandra
  expose:
    - 9410
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - cassandra:storage
query:
  image: openzipkin/zipkin-query:1.19.1
  environment:
    # Remove TRANSPORT_TYPE and unlink collector to disable tracing
    - TRANSPORT_TYPE=scribe
    - STORAGE_TYPE=cassandra
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - cassandra:storage
    - collector
web:
  image: openzipkin/zipkin-web:1.19.1
  environment:
    # Remove TRANSPORT_TYPE and unlink collector to disable tracing
    - TRANSPORT_TYPE=scribe
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - collector
    - query
