# This file uses the version 1 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-1
#
# It runs the zipkin-cassandra, zipkin-query, and zipkin-web containers, as well
# as the legacy zipkin-collector container, and uses docker container linking to
# wire the containers together.

storage:
  image: openzipkin/zipkin-cassandra:1.8.4
  ports:
    - 9042:9042

# The zipkin process services the UI, and also exposes a POST endpoint that
# instrumentation can send trace data to. Scribe is enabled by default.
# It can also poll kafka, when the KAFKA_ZOOKEEPER variable is set.
zipkin:
  image: openzipkin/zipkin:1.8.4
  environment:
    - STORAGE_TYPE=cassandra
    # Uncomment to enable self-tracing
    # - SELF_TRACING_ENABLED=true
  ports:
    # Listen port for the Scribe transport
    - 9410:9410
    # Historical port used for the Zipkin HTTP Api
    - 9411:9411
    # Zipkin UI used to be on a separate process listening on port 8080
    - 8080:9411
  links:
    - storage
