# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to run the
# zipkin-cassandra container instead of the zipkin-mysql container.

version: '2'

services:
  # Run Cassandra instead of MySQL
  storage:
    image: openzipkin/zipkin-cassandra:1.10.0
    container_name: cassandra
    ports:
      - 9042:9042

  # Switch storage type to Cassandra
  zipkin:
    image: openzipkin/zipkin:1.10.0
    environment:
      - STORAGE_TYPE=cassandra
      # When overriding this value, note the minimum supported version is 2.2
      - CASSANDRA_CONTACT_POINTS=cassandra
    depends_on:
      - storage

  dependencies:
    environment:
      - STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=cassandra
