cassandra:
  image: quay.io/openzipkin/zipkin-cassandra:1.4.1
  ports:
    - 9042:9042
collector:
  image: quay.io/openzipkin/zipkin-collector:1.4.1
  environment:
    - BLOCK_ON_CASSANDRA=true
  expose:
    - 9410
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - cassandra:db
query:
  image: quay.io/openzipkin/zipkin-query:1.4.1
  environment:
    - BLOCK_ON_CASSANDRA=true
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - cassandra:db
web:
  image: quay.io/openzipkin/zipkin-web:1.4.1
  links:
    - query
  ports:
    - 8080:8080
    - 9990:9990
