mysql:
  image: openzipkin/zipkin-mysql:1.37.0
  ports:
    - 3306:3306
query:
  image: openzipkin/zipkin-query:1.37.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
  expose:
    # The http api is mounted at /api/v1
    - 9411
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9901
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - mysql:storage
web:
  image: openzipkin/zipkin-web:1.37.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  expose:
    # Web UI is mounted at the root, and the http api under /api/v1
    - 8080
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9990
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query
