global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']
    metric_relabel_configs:
      # Response code count
      - source_labels: [__name__]
        regex: '^counter_status_(\d+)_(.*)$'
        replacement: '${1}'
        target_label: status
      - source_labels: [__name__]
        regex: '^counter_status_(\d+)_(.*)$'
        replacement: '${2}'
        target_label: path
      - source_labels: [__name__]
        regex: '^counter_status_(\d+)_(.*)$'
        replacement: 'http_requests_total'
        target_label: __name__
      # Received message count
      - source_labels: [__name__]
        regex: '(?:gauge|counter)_zipkin_collector_(.*)_([^_]*)'
        replacement: '${2}'
        target_label: transport
      - source_labels: [__name__]
        regex: '(?:gauge|counter)_zipkin_collector_(.*)_([^_]*)'
        replacement: 'zipkin_collector_${1}'
        target_label: __name__
